-- COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS

-- CONTANDO OS REGISTROS DE UMA TABELA

SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*)
FROM CLIENTE;

-- OPERADOR GROUP BY

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

-- PERFORMANCE EM OPERADORES LOGICOS

/* 1 MILHAO DE REGISTROS

PARA CONTAR
SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE
GROUP BY SEXO;

SELECT CIDADE, COUNT(*) FROM CLIENTE
GROUP BY CIDADE;

CONDICAO
SEXO = F
CIDADE = RIO DE JANEIRO

SITUACAO - TRATANDO COM OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE CIDADE = 'RIO DE JANEIRO'
AND SEXO = 'F';

 */