-- PRIMEIRA FORMA NORMAL

/*
1ª REGRA - TODO CAMPO VETORIZADO SE TORNA OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC] -> CARROS

2ª REGRA - TODO CAMPO MULTIVALORIZADO SE TORNARÁ OUTRA TABELA.
QUANDO CAMPO FOR DIVISIVEL

3ª REGRA - TODA TABELA NECESSITA DE PELO MNEOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO SENDO UNICO.
ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY

