/* ARMAZENAR LIVROS DA EMPRESA
	ESCOPO DADOS DOS LIVROS APENAS
	QUERIES
	TRAZER TODOS OS DADOS
	TRAZER NOME DO LIVRO E NOME DA EDITORA
	TRAZER NOME DO LIVRO E UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO
	TRAZER NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO
	TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO
	TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO (QUESTÃO DESAFIO)
*/

-- CRIAÇÃO DO DATABASE

CREATE DATABASE LIVRARIA;

-- CRIAÇÃO DA TABELA

CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(20),
	NOME_DO_AUTOR VARCHAR(20),
	SEXO_DO_AUTOR CHAR(1),
	NUMERO_DE_PAGINAS INT(5),
	NOME_DA_EDITORA VARCHAR(20),
	VALOR_DO_LIVRO FLOAT(5,2),
	UF_DA_EDITORA CHAR(2),
	ANO_DA_PUBLICACAO CHAR(4)

);

-- INSERÇÃO DOS DADOS

-- "MANUALMENTE"

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO) VALUES ('Cavaleiro Real', 'Ana Claudia', 'F', 465, 'ATLAS', 49.9, 'RJ', 2009);

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO) VALUES ('SQL para leigos', 'João Nunes', 'M', 450, 'ADDISON', 98, 'SP', 2018);

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO) VALUES ('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'ATLAS', 45, 'RJ', 2008);

-- CARREGAR ARQUIVO

LOAD DATA INFILE "C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\Exercicio_Livraria.txt" INTO TABLE LIVROS;

INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF_DA_EDITORA, ANO_DA_PUBLICACAO) VALUES ('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', '2018'), ('Habitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', '2019'), ('A Casa Marrom', 'Hermes Macedo', 'M', 250, 'Bubba', 60, 'MG', '2016'), ('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100, 'ES', '2015'), ('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', '2011'), ('Copas Inesqueciveis', 'Marco Alcantara', 'M', 200, 'Larson', 130.98, 'RS', '2018'), ('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'SP', '2017');

-- TRAZER TODOS OS DADOS

SELECT * FROM LIVROS;

-- TRAZER NOME DO LIVRO E NOME DA EDITORA

SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

-- TRAZER NOME DO LIVRO E UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO

SELECT NOME_DO_LIVRO, UF_DA_EDITORA FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M';

-- TRAZER NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO

SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS
WHERE SEXO_DO_AUTOR = 'F';

-- TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO

SELECT VALOR_DO_LIVRO FROM LIVROS
WHERE UF_DA_EDITORA = 'SP';

-- TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO (QUESTÃO DESAFIO)

SELECT * FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M'; -- TESTE

SELECT * FROM LIVROS
WHERE UF_DA_EDITORA = 'SP'; UF_DA_EDITORA = 'RJ'; -- NÃO

SELECT * FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M' AND UF_DA_EDITORA = 'SP' OR UF_DA_EDITORA = 'RJ'; -- NÃO, MAS PUXOU INFOS DE SP E RJ

SELECT * FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M'
WHERE UF_DA_EDITORA = 'SP' OR UF_DA_EDITORA = 'RJ'; -- AINDA NÃO

SELECT * FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M'
AND UF_DA_EDITORA IN ('SP', 'RJ'); -- BINGO!