-- Deletando registros com a clausula delete
-- CUIDADO!!! Faça sempre um SELECT para conferir os dados.
-- Novamente, extremamente recomendado utilizar WHERE para filtrar de DELETAR dados inportantes.

DELETE FROM CLIENTE;

SELECT COUNT(*) FROM CLIENTE; -- Antes de aplicar a função DELETE como boa pratica utilizar comando COUNT para identificar total de registros.

SELECT COUNT(*) FROM CLIENTE
WHERE NOME = 'ANA';

DELETE FROM CLIENTE
WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE;

INSERT INTO CLIENTE VALUES('CARLA', 'F', 'C.LOPES@UOL.COM', 45638854, '4575-0048', 'RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

SELECT * FROM CLIENTE;

DELETE FROM CLIENTE;
WHERE NOME = 'CARLA'
OR EMAIL = 'LILIAN@HOTMAIL.COM';

-- TROCAR 'DELETE' POR 'SELECT *' PARA VALIDAR SE FILTRO ESTÁ CORRETO

SELECT * FROM CLIENTE;
WHERE NOME = 'CARLA'
OR EMAIL = 'LILIAN@HOTMAIL.COM'; -- TRAZ TODO MUNDO DAS DUAS CONDIÇÕES

DELETE FROM CLIENTE;
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT * FROM CLIENTE;
