-- 18 - SELEÇÕES

-- FILTRAR POR COLUNA = PROJEÇÃO

-- PROJEÇÃO -> SELECT

-- SELEÇÃO -> WHERE

-- FILTRANDO DADOS COM WHERE E LIKE

SELECT NOME, TELEFONE FROM CLIENTE;

-- FILTRANDO

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

-- UTILIZANDO O LIKE

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

-- CARACTER CORINGA % -> QUALQUER COISA

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';
